name: pos
description: We connect suppliers, retailers and customers.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.5+19

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4
  flutter_keyboard_visibility: ^5.4.1
  shared_preferences: ^2.2.2
  timeago: ^3.5.0
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  location: ^5.0.3
  geolocator: ^10.0.1
  flutter_onboard: ^2.0.0
  onesignal_flutter: ^3.5.0
  dio: ^5.3.3
  ionicons: ^0.2.2
  youtube_player_flutter: ^8.1.2
  firebase_dynamic_links: ^5.4.2
  share_plus: ^7.2.1
  url_launcher: ^6.1.11
  money_formatter: ^0.0.4
  lottie: ^2.3.2
  latlong2: ^0.8.2
  animations: ^2.0.8
  carousel_slider: ^4.2.1
  http: ^0.13.6
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/1024.png"

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
