List hobbiesList = [
                                "Art",
                                "Science",
                                "Engineering",
                                "Politics",
                                "Fashion",
                                "Sports",
                                "Music",
                                "Writing",
                                "Photography",
                                "Gaming",
                                "Dance",
                                "Outdoor Activities",
                                "Dance",
                                "Volunteering",
                                "Yoga and Meditation",
                                "Film and Cinema",
                                "Traveling",
                                "Technology and Coding",
                                "Literature and Book Clubs",
                                "Gardening",
                                "Cooking or Baking",
                                "DIY and Crafts",
                                "Sustainability",
                                "Language Learning",
                                "Collecting",
                                "Fitness and Exercise",
                            ];